### PR TITLE
Namespaces fix

### PR DESCRIPTION
**Pull request by goulart-paul**
Previously #72.

### CODE REVIEW

**Comment by imciner2** [comment]
@mlubin @bstellato are the changes from this PR still needed?

**Comment by bstellato** [comment]
I think we already fixed it for most of the API functions that could conflict with other software.

**Comment by imciner2** [comment]
I'll close this PR then. If there are any other namespace issues, we can open a new PR against the more recent code.

**Comment by mlubin** [comment]
I'm not aware of any current conflicts, but it's a good general practice to prefix all exported symbols consistently.

**Pull request closed without merging**
