### PR TITLE
Namespaces fix

### LINKED ISSUE #67: exported symbols and namespace issues
Both [OSQP](https://github.com/oxfordcontrol/osqp/blob/bb5bb360b6dee9725256cb6953c774a82520edda/include/auxil.h#L107) and [ECOS](https://github.com/embotech/ecos/blob/14e89089c76a99648e01b63c9503df7e3360271e/ecos_bb/ecos_bb.c#L239) define and export a function called `store_solution` with a signature that's basically identical at the linking level. I discovered this by watching `osqp_solve` crash with a stack trace that pointed to ECOS...

I'm not familiar with all of the subtleties of visibility issues in C libraries, but I think the following defensive proposal would prevent issues like this:

(Proposal) Functions defined by OSQP should be either:
1. prefixed with `osqp_`, or
2. marked as `static`, and hence only visible within a single .c file.

If ECOS followed this proposal, the issue would've been avoided since their version of `store_solution` can be marked `static`.

What do you think?

### PR DESCRIPTION
**Pull request by bstellato**
Various changes to fix namespace issues in C++ projects including OSQP.

Fixes #67 .

### CODE REVIEW

**Comment by mlubin** [comment]
I recently found some additional conflicts with ECOS that aren't addressed in this PR:
`tic` and `toc`:
https://github.com/oxfordcontrol/osqp/blob/f02810e2fbb48e758ab3f6875faeb4591f9836ff/src/util.c#L272
https://github.com/embotech/ecos/blob/14e89089c76a99648e01b63c9503df7e3360271e/src/timer.c#L81

`handle_ctrlc`:
https://github.com/oxfordcontrol/osqp/blob/f02810e2fbb48e758ab3f6875faeb4591f9836ff/src/ctrlc.c#L56
https://github.com/embotech/ecos/blob/14e89089c76a99648e01b63c9503df7e3360271e/src/ctrlc.c#L89

`ldl_l_solve` and `ldl_l_ltsolve` (because both libraries include the LDL source)

**Comment by mlubin** [comment]
Thanks for addressing this by the way :)
My PR to ECOS hasn't gotten anywhere.

**Comment by mlubin** [comment]
By the way, `tic`, `toc`, and `handle_ctrlc` are conflicts with ECOS in OSQP 0.4.0. I'm unable to link ECOS and OSQP in the same binary because of this. Would it help if I provided a patch?

**Comment by bstellato** [comment]
Yes that would help for sure! Would you mind making a PR for the `0.4.1` branch?
I guess the `ldl` part is now gone.

**Comment by goulart-paul** [comment]
I am going to reopen this on the develop-1.0 branch

**Pull request closed without merging**
